version: "3"

services:
  app:
    image: rsl-learning-platform:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: rsl-learning-platform-app
    ports:
      - "8080:8090"
    depends_on:
      - db
    env_file:
      - app.env

  db:
    image: postgres:13.14-alpine3.19
    container_name: rsl-learning-platform-db
    env_file:
      - db.env
